# Generated by Django 5.2.8 on 2025-11-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField(help_text='enter product id1:')),
                ('id2', models.IntegerField(help_text='enter product id2:')),
                ('name1', models.CharField(help_text='enter product name1:', max_length=10)),
                ('name2', models.CharField(help_text='enter product name2:', max_length=15)),
            ],
        ),
    ]
